/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/mgmg_model.glb -o src/components/Mgmg.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mgmg(props) {
  const { nodes, materials } = useGLTF('/models/mgmg_model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['Material.004']} position={[0, 0.98, -1.382]} rotation={[Math.PI / 2, 0, 0]} scale={226.74} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['Material.005']} position={[0, 0.98, -1.382]} rotation={[Math.PI / 2, 0, 0]} scale={226.74} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['Material.003']} position={[0, 0.98, -1.382]} rotation={[Math.PI / 2, 0, 0]} scale={226.74} />
      <mesh geometry={nodes.Curve003.geometry} material={materials['Material.002']} position={[0, 0.98, -1.382]} rotation={[Math.PI / 2, 0, 0]} scale={226.74} />
    </group>
  )
}

useGLTF.preload('/models/mgmg_model.glb')
